name: "Build iOS app"

on:
  # manual trigger but change to any supported event
  # see addl: https://www.andrewhoog.com/post/how-to-build-react-native-android-app-with-github-actions/#3-run-build-workflow
  workflow_dispatch:
    branches: [main]

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      # Cache para acelerar
      - name: Cache Flutter
        uses: actions/cache@v4
        id: flutter-cache
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}

      - name: Setup Flutter
        if: steps.flutter-cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # - name: Build iOS (sem assinatura)
      #   run: |
      #     flutter build ios --debug

      - name: Build iOS debug
        run: |
          flutter build ios --release --no-codesign

      # Para builds assinados (requer certificados)
      # - name: Build iOS com assinatura
      #   run: |
      #     flutter build ios --release
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
      
      # - name: Build IPA
      #   run: |
      #     cd ios
      #     xcodebuild -workspace Runner.xcworkspace \
      #               -scheme Runner \
      #               -configuration Release \
      #               -destination generic/platform=iOS \
      #               -archivePath build/Runner.xcarchive \
      #               archive
          
      #     xcodebuild -exportArchive \
      #               -archivePath build/Runner.xcarchive \
      #               -exportPath build \
      #               -exportOptionsPlist ExportOptions.plist
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/*.ipa